# Generated by Django 2.2 on 2021-05-25 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo_App', '0006_auto_20210524_0422'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['start']},
        ),
        migrations.RenameField(
            model_name='event',
            old_name='date',
            new_name='end',
        ),
        migrations.RemoveField(
            model_name='event',
            name='user',
        ),
        migrations.AddField(
            model_name='event',
            name='start',
            field=models.DateField(default='2021-05-20'),
            preserve_default=False,
        ),
    ]
