# Generated by Django 2.2 on 2021-05-25 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo_App', '0007_auto_20210525_0920'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['start_date', 'end_date']},
        ),
    ]
