# Generated by Django 2.2 on 2021-05-25 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo_App', '0009_auto_20210525_0619'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['date']},
        ),
        migrations.RenameField(
            model_name='event',
            old_name='end',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='start',
        ),
    ]
