# Generated by Django 2.2 on 2021-05-26 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo_App', '0010_auto_20210525_1244'),
        ('ToDo_App', '0013_auto_20210526_0412'),
    ]

    operations = [
    ]
